use crate::{
    enchantments::Enchantment,
    item::{target_item, Item},
};

pub fn presets() -> Vec<Vec<Item>> {
    vec![
        target_item!(
            ItemType::Pickaxe,
            Enchantment::Unbreaking,
            Enchantment::Mending,
            Enchantment::Efficiency,
            Enchantment::Fortune
        ),
        target_item!(
            ItemType::Pickaxe,
            Enchantment::Unbreaking,
            Enchantment::Mending,
            Enchantment::Efficiency,
            Enchantment::SilkTouch
        ),
        target_item!(
            ItemType::Sword,
            Enchantment::Unbreaking,
            Enchantment::Mending,
            Enchantment::Sharpness,
            Enchantment::Looting,
            Enchantment::FireAspect
        ),
        target_item!(
            ItemType::Axe,
            Enchantment::Unbreaking,
            Enchantment::Mending,
            Enchantment::Efficiency,
            Enchantment::Sharpness,
            Enchantment::SilkTouch
        ),
        target_item!(
            ItemType::Shovel,
            Enchantment::Unbreaking,
            Enchantment::Mending,
            Enchantment::Efficiency,
            Enchantment::SilkTouch
        ),
        target_item!(
            ItemType::Hoe,
            Enchantment::Unbreaking,
            Enchantment::Mending,
            Enchantment::Efficiency,
            Enchantment::Fortune
        ),
        target_item!(
            ItemType::Bow,
            Enchantment::Unbreaking,
            Enchantment::Mending,
            Enchantment::Power,
            Enchantment::Flame
        ),
        target_item!(
            ItemType::Bow,
            Enchantment::Unbreaking,
            Enchantment::Infinity,
            Enchantment::Power,
            Enchantment::Flame
        ),
        target_item!(
            ItemType::Crossbow,
            Enchantment::Unbreaking,
            Enchantment::Mending,
            Enchantment::QuickCharge,
            Enchantment::Piercing
        ),
        target_item!(
            ItemType::Trident,
            Enchantment::Unbreaking,
            Enchantment::Mending,
            Enchantment::Loyalty,
            Enchantment::Channeling,
            Enchantment::Impaling
        ),
        target_item!(
            ItemType::Trident,
            Enchantment::Unbreaking,
            Enchantment::Mending,
            Enchantment::Riptide,
            Enchantment::Impaling
        ),
        target_item!(
            ItemType::Helmet,
            Enchantment::Unbreaking,
            Enchantment::Mending,
            Enchantment::ProjectileProtection,
            Enchantment::Respiration,
            Enchantment::AquaAffinity,
            Enchantment::Thorns
        ),
        target_item!(
            ItemType::Chestplate,
            Enchantment::Unbreaking,
            Enchantment::Mending,
            Enchantment::BlastProtection,
            Enchantment::Thorns
        ),
        target_item!(
            ItemType::Leggings,
            Enchantment::Unbreaking,
            Enchantment::Mending,
            Enchantment::Protection,
            Enchantment::Thorns,
            Enchantment::SwiftSneak
        ),
        target_item!(
            ItemType::Boots,
            Enchantment::Unbreaking,
            Enchantment::Mending,
            Enchantment::FireProtection,
            Enchantment::FeatherFalling,
            Enchantment::DepthStrider,
            Enchantment::SoulSpeed,
            Enchantment::Thorns
        ),
        target_item!(
            ItemType::Shield,
            Enchantment::Unbreaking,
            Enchantment::Mending
        ),
        target_item!(
            ItemType::Elytra,
            Enchantment::Unbreaking,
            Enchantment::Mending
        ),
        target_item!(
            ItemType::Shears,
            Enchantment::Unbreaking,
            Enchantment::Mending,
            Enchantment::Efficiency
        ),
        target_item!(
            ItemType::FlintAndSteel,
            Enchantment::Unbreaking,
            Enchantment::Mending
        ),
        target_item!(
            ItemType::FishingRod,
            Enchantment::Unbreaking,
            Enchantment::Mending,
            Enchantment::LuckOfTheSea,
            Enchantment::Lure
        ),
        target_item!(
            ItemType::CarrotOnAStick,
            Enchantment::Unbreaking,
            Enchantment::Mending
        ),
        target_item!(
            ItemType::WarpedFungusOnAStick,
            Enchantment::Unbreaking,
            Enchantment::Mending
        ),
    ]
}
